api/urls.py
from django.urls import path,include  
from . import views
from . import api
from .api import TaskListCreateAPIView,TaskUpdateAPIView,TaskDeleteAPIView,SubTaskListCreateAPIView,SubTaskUpdateAPIView, \
   SubTaskDeleteAPIView,UserUpdateAPIView,PasswordUpdateAPIView,UserCreationAPIView,CreateAuthToken,TaskDetailAPIView,SubTaskDetailAPIView
from rest_framework.authtoken.views import obtain_auth_token



urlpatterns = [

   path('', api.ApiSummary, name="api-summary"),
   path('tasks/',TaskListCreateAPIView.as_view(),name='task-list'),
   path('task/<int:pk>/',TaskDetailAPIView.as_view(),name='task-detail'),
   path('task/<int:pk>/update/',TaskUpdateAPIView.as_view(),name='task-edit'),
   path('task/<int:pk>/delete/',TaskDeleteAPIView.as_view(),name="task-delete"),
   path('task/<int:pk>/subtasks/',SubTaskListCreateAPIView.as_view(),name='subtask-list'),
   path('subtask/<int:pk>/',SubTaskDetailAPIView.as_view(),name='subtask-detail'),
   path('subtask/<int:pk>/update/',SubTaskUpdateAPIView.as_view(),name="subtask-edit"),
   path('subtask/<int:pk>/delete/',SubTaskDeleteAPIView.as_view(),name="subtask-delete"),
   path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
   path('api-auth/update-user/',UserUpdateAPIView.as_view(),name='update-user'),
   path('api-auth/update-password/',PasswordUpdateAPIView.as_view(),name='update-password'),
   path('api-auth/register/',UserCreationAPIView.as_view(),name="user-register"),

   path('api-auth/api-token-auth/',CreateAuthToken.as_view(), name='api_token_auth'),

]

do_do_list/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('api/',include('api.urls')),

    
]

main/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [

    path('',HomeView.as_view(),name="home"),
    path('delete/<int:pk>/',DeleteTask.as_view(),name='delete_task'),
    path('update/<int:pk>/',UpdateTask.as_view(),name='update_task'),
    path('success/<int:pk>/',SetSuccess.as_view(),name='set_success'),
    path('signup/',UserSignUp.as_view(),name='user_signup'),
    path('login/',UserLogin.as_view(),name='user_login'),
    path('logout/',UserLogout.as_view(),name='user_logout'),
    path('edit_user/',edit_user.as_view(),name='edit_user'),
    path('change_password/',ChangePassword.as_view(),name='change_password'),

    path('subtask/<int:pk>/',SubtaskView.as_view(),name='subtask'),
    path('check/<int:pk>/',CheckSubTask.as_view(),name='check'),
    path('reset/<int:pk>/',ResetSubTask.as_view(),name="reset_subtasks"),
    path('remove/<int:pk>/',RemoveSubTask.as_view(),name="remove_subtask"),
    path('update_subtask/<int:pk>/',UpdateSubtask.as_view(),name='update_subtask'),
    path('delete_all_subtasks/<int:pk>/',DeleteAllSubtask.as_view(),name='delete_all_subtasks'),

    path('calendar/',CalendarView.as_view(), name='calendar'),
    
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='settings/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='settings/password_reset_complete.html'),name='password_reset_complete'),
    path('account_activation/<uidb64>/<token>', views.account_activation, name='account_activation'),
   
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from datetime import date
from django.urls import reverse


class Task(models.Model):

    STATUS = (

        ('W', 'Waiting'),
        ('I', 'Inprogress'),
        ('S', 'Success'),
        ('F', 'Failed'),
        ('O', 'Overdue'),
    )
   


    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    note = models.TextField(max_length=500,null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=timezone.now)
    start_time = models.TimeField()
    due_date = models.DateField(default=timezone.now)
    due_time = models.TimeField()
    status = models.CharField(max_length = 1, choices=STATUS,default="W")

    def __str__(self):

        return f'{self.title}'
    

    @property
    def get_start(self):

        url = reverse('update_task',args=(self.pk,))
        return f'<a href="{url}"><small>{self.start_time}</small><i> ({self.title})</i></a><hr>'
    
    @property
    def get_due(self):

        url = reverse('update_task',args=(self.pk,))
        return f'<a href="{url}"><small>{self.due_time}</small><i> ({self.title})</i></a><hr>'



@receiver(post_save, sender=Task)
def handler_function(sender, instance, created, **kwargs):
    if  created:
        current_date = date.today()
        if instance.due_date < current_date:
            instance.status = "O"
        elif instance.start_date <= current_date:
            instance.status = "I"
        else:
             instance.status = "W"
        instance.save()


class SubTask(models.Model):

    title = models.CharField(max_length=100, null=True, blank=True)
    subnote = models.TextField(max_length=500,null=True, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    status = models.BooleanField(default=False)
    task = models.ForeignKey(Task,on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):

        return f'{self.task}-{self.title}-{self.updated}'

main/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,CreateView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.views import LoginView,LogoutView,PasswordChangeView,PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse_lazy,reverse
from .forms import UserLoginform,RegisterForm,ResetPasswordForm,CreateTaskForm,UpdateTaskform,CreateSubTaskForm,UpdateSubTaskForm,UserForm,ChangePasswordForm
from .models import Task,SubTask
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.shortcuts import get_object_or_404
from .mixins import UserIsAnonymous
from datetime import date,timedelta
from django.db.models import Q
from django.utils import timezone
from .utils import Calendar
import calendar
from django.utils.safestring import mark_safe

from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from .tokens import account_activation_token
#prevent error related force_text not found
from django.utils.encoding import force_str as force_text




class HomeView(LoginRequiredMixin,View):

    def get(self,request):

        select = request.GET.get('select',None)
        search = request.GET.get('search',"")
        request.session['searching'] = search

        if select is not None:
            if select == "A":
                tasks = Task.objects.filter(user=request.user,title__icontains=search).order_by('-status')
            else:
                tasks = Task.objects.filter(user=request.user,status=select,title__icontains=search).order_by('-due_date') 
            request.session['selection'] = select      
        else:
            tasks = Task.objects.filter(user=request.user).order_by('-status')
                  
        count = tasks.count()
        p = Paginator(tasks,4)
        page = self.request.GET.get('page')

        try:
            tasks = p.page(page)
        except PageNotAnInteger:
            tasks = p.page(1)
        except EmptyPage:
            tasks = p.page(p.num_pages)

        form = CreateTaskForm()
        context = {'form':form,'tasks':tasks,'count':count}
        return render(request,'main/home.html',context)
    
    def post(self,request):

        form = CreateTaskForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user

            if data.due_date < data.start_date:

                messages.error(request,'due date need to greater than start date')
                return redirect('home')

            if (data.due_date == data.start_date) and (data.due_time < data.start_time):
                messages.error(request,'due time need to greater than start time')
                return redirect('home')
            
            data.save()
            messages.success(request,'You saved new to do task')

        else:
            for error in list(form.errors.values()):
                messages.error(request,error)

        return redirect('home')
    

class DeleteTask(LoginRequiredMixin,View):

    def post(self,request,pk):
        task = get_object_or_404(Task,pk=pk)
        if task.user == request.user:
                task.delete()
                messages.success(request,'you successfully removed your task')
        else:
            messages.error(request,'Permission denied')
        return redirect('home')
    

class UpdateTask(LoginRequiredMixin,View):

    def get(self,request,pk):
        task = get_object_or_404(Task,pk=pk)
        if task.user == request.user:
            form = UpdateTaskform(instance=task)  
            context={'form':form,'title':'task','task':task}
        else:
            messages.error(request,'Permission denied')
            return redirect('home')
        return render(request,'main/update_task.html',context)

    def post(self,request,pk):
        task = get_object_or_404(Task,pk=pk)
        if task.user == request.user:
            form = UpdateTaskform(request.POST,instance=task)
            if form.is_valid():
                data = form.save(commit=False)   
                if data.due_date < data.start_date:
                    messages.error(request,'due date need to greater than start date')
                    return redirect('update_task',pk)

                if (data.due_date == data.start_date) and (data.due_time < data.start_time):
                    messages.error(request,'due time need to greater than start time')
                    return redirect('update_task',pk)
                
                form.save()
                messages.success(request,'Task modified')
            else:
                for error in list(form.errors.values()):
                    messages.error(request,error)
        else:
            messages.error(request,'Permission denied')

        return redirect('home')
    


class SetSuccess(LoginRequiredMixin,View):

    def post(self,request,pk):
        task = get_object_or_404(Task,pk=pk)
        if task.user == request.user:
            if task.status != "S":
                task.status = "S"
                task.save()
                messages.success(request,'Task status modified to success')
            else:
                messages.info(request,'Task already success nothing to do')
        else:
            messages.error(request,'Permission denied this task is not yours')
        return redirect('home')

   
class UserLogin(SuccessMessageMixin,LoginView):

    template_name = 'main/login.html'
    form_class = UserLoginform
    redirect_authenticated_user = True
 
    def get_success_message(self, cleaned_data):
         
         return(f'{self.request.user} has been logged in')
    
    def set_overdue(self,request):
        current_date = date.today()
        tasks = Task.objects.filter(user=request.user,due_date__lt=current_date).exclude(Q(status="S")|Q(status="F")|Q(status="O")).update(status="O")

    def set_inprog(self,request):
        current_date = date.today()
        current_time = timezone.now()
        tasks = Task.objects.filter(user=request.user,start_date=current_date,due_time__gt=current_time,status="W").update(status="I")

    
    def form_invalid(self,form):
        
        for key, error in list(form.errors.items()):
            
            if key == 'captcha' and error[0] == 'This field is required.':
                messages.error(self.request, "You must pass the reCAPTCHA test")
                continue
            messages.error(self.request, error) 

        return self.render_to_response(self.get_context_data(form=form))
    
    def get_success_url(self):
        self.set_overdue(self.request)
        self.set_inprog(self.request)
        return reverse('home')
    

class UserLogout(LogoutView):
  
    def get_success_url(self):

        return reverse_lazy('home')
    

class UserSignUp(UserPassesTestMixin,SuccessMessageMixin,CreateView):

    template_name = 'main/signup.html'
    form_class = RegisterForm
    success_message = "%(username)s was created successfully"
    
    def test_func(self):
        if self.request.user.is_anonymous:
            return True
        else:
            return False
    
    def handle_no_permission(self):
        messages.warning(self.request,'You already logged in ')
        return redirect('home')

   
    def form_valid(self, form):  
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        subject = 'Activate Your Account'
        message = render_to_string('settings/account_activation_email.html', {
        'user':user,
        'domain':current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token':account_activation_token.make_token(user),})
           
        try:
                user.email_user(subject=subject, message=message)
                messages.success(self.request,'To finish registration please check your mailbox including spam folder and follow instructions')
        except:
            messages.error(self.request,'Mail Server Connection problem, please turn to website admin')


        return super().form_valid(form)
   
    def form_invalid(self, form):
        
        for key, error in list(form.errors.items()):
            if key == 'captcha' and error[0] == 'This field is required.':
                messages.error(self.request, "You must pass the reCAPTCHA test")
                continue
            messages.error(self.request, error)
        return super().form_invalid(form)
    
    def get_success_url(self):
        return reverse_lazy('user_login')
    
    
    def get_success_message(self, cleaned_data):

        return self.success_message % dict(
            cleaned_data,
            username=self.object.username
        )


def account_activation(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        
    except():
        pass

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request,'Your registration finished now please login')
        return redirect('user_login')

    else:
        return render(request, 'settings/activation_invalid.html')





class edit_user(LoginRequiredMixin,View):

    def get(self,request):
        user = request.user
        form = UserForm(instance=user)
        context={'form':form}
        return render(request,'main/edit_user.html',context)

    def post(self,request):

        user = request.user

main/templates/main/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>To do application</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
        <!-- MDB -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.2.0/mdb.min.css" rel="stylesheet" />
        <!--OWN css-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <!--Jquery-->
        <script
			  src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
			  integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8="
			  crossorigin="anonymous"></script>

        {% include "main/navbar.html" %} 

    </head>
    <body>
 
     {% block content %}
     {% endblock content %}
        <!-- MDB -->
        <script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/8.2.0/mdb.umd.min.js"></script>

    </body>


    
</html>

main/templates/main/calendar.html
{% extends "main/base.html" %}

{% block content %}

<section class="vh-100" >
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="py-5">
        <div class="card rounded-3 shadow-custom2">
          <div class="card-body p-4">
            <div class="clearfix">
                
                <a class="btn btn-info left" id="btn-calendar" href="{% url 'calendar' %}?{{prev_month}}"><i class="fa-solid fa-left-long"></i> Previous Month </a>
                <a class="btn btn-info right" id="btn-calendar" href="{% url 'calendar' %}?{{next_month }}">Next Month <i class="fa-solid fa-right-long"></i></a>
            </div>
            {{ calendar }}


                </div>
            </div>
         </div>
    </div>
     
</div>

<div class="row justify-content-center">
  <a href="{% url 'home' %}"  class="btn btn-outline-secondary mx-2 text-center py-3 my-4 w-75"><i class="fa-solid fa-circle-arrow-left fa-lg"></i> Home</a>
</div>
</section>
{% endblock content %}

main/templates/main/edit_user.html
{% extends "main/base.html" %}
{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="py-5">

            <div class="card shadow-custom">
                <div class="card-body">

                    {% include "main/messages.html" %}
                    <h1>Edit User ({{request.user.username}}) </h1>
                    <hr>
                    <!-- edit form column -->
                    <div class="col-md-9 personal-info py-5 my-5 ">
                        <h3>Personal info</h3>
                        
                        <form class="form-horizontal" role="form" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-lg-8">
                                {{form}}
                            </div>
                        </div>
                            <button type="submit" class="btn btn-primary my-3 btn">Submit</button>
                            <a href="{% url 'change_password' %}"  class="btn btn-dark my-3" data-mdb-tooltip-init title="Back" data-mdb-placement="bottom">Change Password</a>
                            <a href="javascript:history.back()"  class="btn btn-outline-secondary my-3" data-mdb-tooltip-init title="Back" data-mdb-placement="bottom"><i class="fa-solid fa-circle-arrow-left fa-lg"></i></a>
                        </form>
                    </div>
                </div>
            </div>
       </div>
    </div>
</section>
{% endblock content  %}

main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}

<section class="vh-100" >
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="py-5">
        <div class="card rounded-3 shadow-custom2">
          <div class="card-body p-4">
            {% include "main/messages.html" %}

            <h4 class="text-center my-3 pb-3">Add new task to do</h4>

            <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
            {% csrf_token %}
              
              <div class="col-12">
              
                <div data-mdb-input-init class="form-inline py-1">
                    {% for field in form %}
                    <div class="py-1 my-1">{{field}}</div>
                    {% endfor %}                  
                </div>
                <button type="submit" class="btn btn-primary" data-mdb-tooltip-init title="Save" data-mdb-placement="bottom"><i class="fa-solid fa-floppy-disk"></i></button>
                
               
              </div>
              
              {{form.media}}  
            </form>
            
          <div class="row row-cols-lg-auto g-3 justify-content-left align-items-center mb-4 mt-4 pb-2">
                <div class="w-25 text-center">
                <form method="GET">
                <select name="select" id="select" class="form-select form-control form-control-sm" aria-label="Default select example">
                  <option value="A"  {% if request.session.selection == "A"%} selected {% endif %}>All</option>
                  <option value="W"  {% if request.session.selection == "W"%} selected {% endif %}>Waiting</option>
                  <option value="I"  {% if request.session.selection == "I"%} selected {% endif %}>Inprogress</option>
                  <option value="S"  {% if request.session.selection == "S"%} selected {% endif %}>Success</option>
                  <option value="F"  {% if request.session.selection == "F"%} selected {% endif %}>Failed</option>
                  <option value="O"  {% if request.session.selection == "O"%} selected {% endif %}>Overdue</option>     
                </select>
               <!-- </form> -->
                </div>
                       
                <div class="input-group w-25">     
                  <div class="form-outline" data-mdb-input-init>
                    <input type="search" name="search" value="{% if request.session.searching %}{{request.session.searching}}{% endif %}" class="form-control form-control-sm" />
                    <label class="form-label">Search</label>
                  </div>
                  <button type="submit" class="btn btn-primary" data-mdb-ripple-init>
                    <i class="fas fa-search"></i>
                  </button>             
                </div>
                </form>
            </div>

 


             <h6 class="text-center my-3"><i>Your current tasks ({{count}})</i></h6>
            <table class="table mb-4">
              <thead>
                <tr>
                  <th scope="col">Todo task</th>
                  <th scope="col">Status</th>
                  <th scope="col">Start date</th>
                  <th scope="col">Due date</th>
                  <th scope="col">Actions</th>
                </tr>
              </thead>
              <tbody>
              {% for task in tasks %}
                <tr>                
                  <td data-mdb-tooltip-init title="{{task.title}}">{{task.title|truncatechars:15}}</td>
                  <td>
                   {% if task.status == "W" %}
                    <h6><span class="badge badge-info">Waiting</span></h6>              
                   {% elif task.status == "I"  %}
                    <h6><span class="badge badge-warning">Inprogress</span></h6>
                   {% elif task.status == "S"  %}
                    <h6><span class="badge badge-success">Success</span></h6>
                   {% elif task.status == "F"  %}
                    <h6><span class="badge badge-danger">Failed</span></h6>
                    {% elif task.status == "O"  %}
                    <h6><span class="badge badge-dark">Overdue</span></h6>
                   {% endif %} 

                  </td>
                  <td>{{task.start_date}}<small> ( <i class="fa fa-hourglass-start" aria-hidden="true"></i>&nbsp;{{task.start_time}})</small></td>
                  <td>{{task.due_date}}<small> ( <i class="fa fa-hourglass-end" aria-hidden="true"></i>&nbsp;{{task.due_time}})</small></td></td>
                  <td>
                    <button type="button" data-mdb-ripple-init data-mdb-modal-init data-mdb-target="#deleteModal-{{task.pk}}" data-mdb-tooltip-init title="Delete" data-mdb-placement="bottom" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash-can"></i></button>
                    <a href="{% url 'update_task' task.pk %}" data-mdb-tooltip-init title="Update" data-mdb-placement="bottom" class="btn btn-warning btn-sm"><i class="fa-solid fa-wrench"></i></a>
                    <a href="{% url 'subtask' task.pk %}" data-mdb-tooltip-init title="Manage subtasks" data-mdb-placement="bottom" class="btn btn-info btn-sm"><i class="fa fa-tasks" aria-hidden="true"></i><small class="text-dark"> ({{task.subtask_set.count}})</small></a>
                    <button type="button" data-mdb-ripple-init data-mdb-modal-init data-mdb-target="#successModal-{{task.pk}}" data-mdb-tooltip-init title="Set success" data-mdb-placement="bottom" class="btn btn-success btn-sm ms-1" {% if task.status == "S" %}disabled{% endif %}><i class="fa-solid fa-circle-check"></i></button>
                  </td>
                </tr>

                 {% include "main/modal.html" %}
              {% endfor %}

              </tbody>
            </table>


                      {% if tasks.has_other_pages %}
                      <nav aria-label="Page navigation example">
                          <ul class="pagination pagination-sm py-3">
                            {% if tasks.has_previous %}
                            <li class="page-item"><a class="page-link text-white mx-1 my-2" style="background-color:#077e58;" href="?page={{tasks.previous_page_number }}{% if request.GET.select %}&select={{request.GET.select}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">Previous</a></li>
                            {% endif%}

                            {% for num  in tasks.paginator.page_range %}
                            {% if tasks.number == num %}
                            <li class="page-item"><a class="page-link text-white  mx-1 my-2" style="background-color:#077e58;"  href="">{{num}}</a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link  text-white mx-1 my-2" style="background-color:#077e58;" href="?page={{ num }}{% if request.GET.select%}&select={{request.GET.select}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">{{num}}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if tasks.has_next %}
                            <li class="page-item"><a class="page-link  text-white mx-1 my-2" style="background-color:#077e58;" href="?page={{tasks.next_page_number }}{% if request.GET.select%}&select={{request.GET.select}}{% endif %}{% if request.GET.search %}&search={{request.GET.search}}{% endif %}">Next</a></li>
                            {% endif %}
                    
                          </ul>
                    </nav>
               
                      {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

             
 <script type="text/javascript">

  jQuery(function() {
    jQuery('#select').change(function() {
        this.form.submit();
    });
});
</script>






{% endblock content %}

main/templates/main/login.html
 {% extends "main/base.html" %}
 {% block content %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container py-5 h-100">       
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="card w-75 shadow-custom">
                <div class="card-body">
                {% include "main/messages.html" %}
                    <form method="POST" action="{% url 'user_login' %}">
                    <h3 class="py-2 text-center">Login</h3>
                    {% csrf_token %}
                    {% for field in form %}
                    <label>{{field.label}}</label><br>
                        {{field}}
                    {% endfor %}          
                    <div class="row mb-4">
                        <div class="col text-center py-1 mb-4">
                        <a class="text-center" href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>
                    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
                    <div class="text-center">
                        <p>Not a member? <a href="{% url 'user_signup' %}">Register</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content%}

main/templates/main/update_task.html
{% extends "main/base.html" %}

{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="py-5">
        <div class="card rounded-3 shadow-custom2">
          <div class="card-body p-4">
          {% include "main/messages.html" %}

            <h4 class="text-center my-3 pb-3">Update {{title}}</h4>

                <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2" method="POST">
                {% csrf_token %}
                    
                <div class="col-12">
                    
                    <div data-mdb-input-init class="form-inline py-1">
                        {% for field in form %}
                        <div class="py-1 my-1">{{field}}</div>
                        {% endfor %}                  
                        </div>
                    <button type="submit" class="btn btn-primary" data-mdb-tooltip-init title="Save" data-mdb-placement="bottom"><i class="fa-solid fa-floppy-disk"></i></button>
                    {% if task %}
                    <a href="{% url 'subtask' task.pk %}" data-mdb-tooltip-init title="Manage subtasks" data-mdb-placement="bottom" class="btn btn-info"><i class="fa fa-tasks" aria-hidden="true"></i><small class="text-dark"> ({{task.subtask_set.count}})</small></a>
                    {% endif %}
                    <a href="javascript:history.back()"  class="btn btn-outline-secondary mx-2" data-mdb-tooltip-init title="Back" data-mdb-placement="bottom"><i class="fa-solid fa-circle-arrow-left fa-lg"></i></a>                  
                    </div>                    
                    {{form.media}}  
                    </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}